import Navbar from "@/components/shared/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Instrument_Sans, Manrope } from "next/font/google";
import "./globals.css";

const instrumental_sans = Instrument_Sans({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MILE",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(instrumental_sans.className, "font-instrumental_sans")}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
