/* eslint-disable @next/next/no-page-custom-font */
import Footer from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "MILE",
  description: "Generated by create next app",
  icons: [
    {
      media: "(prefers-color-scheme: light)",
      url: "/assets/images/logo.svg",
      href: "/assets/images/logo.svg",
    },
    {
      media: "(prefers-color-scheme: dark)",
      url: "/assets/images/logo.svg",
      href: "/assets/images/logo.svg",
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&family=Manrope:wght@200;300;400;500;600;700;800&family=Mulish:wght@200;300;400;500;600;700;800;900&display=swap"
        />
      </head>
      <body className={` flex flex-col min-h-screen`}>
        <Navbar />
        <main className="flex-1 pt-[84px] lg:pt-[120px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
